/*
Deployment script for C:\USERS\SÜKRÜ ÖZDEMIR\DOCUMENTS\VISUAL STUDIO 2015\PROJECTS\ONLINESATISPROJE\ONLINESATISPROJE.WEB\APP_DATA\ONLINESATISDB.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "C:\USERS\SÜKRÜ ÖZDEMIR\DOCUMENTS\VISUAL STUDIO 2015\PROJECTS\ONLINESATISPROJE\ONLINESATISPROJE.WEB\APP_DATA\ONLINESATISDB.MDF"
:setvar DefaultFilePrefix "C_\USERS\SÜKRÜ ÖZDEMIR\DOCUMENTS\VISUAL STUDIO 2015\PROJECTS\ONLINESATISPROJE\ONLINESATISPROJE.WEB\APP_DATA\ONLINESATISDB.MDF_"
:setvar DefaultDataPath "C:\Users\Sükrü Özdemir\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\Sükrü Özdemir\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping [dbo].[FK_dbo.Adres_dbo.Ilce_IlceId]...';


GO
ALTER TABLE [dbo].[Adres] DROP CONSTRAINT [FK_dbo.Adres_dbo.Ilce_IlceId];


GO
PRINT N'Dropping [dbo].[FK_dbo.KullaniciAdresMapping_dbo.Adres_AdresId]...';


GO
ALTER TABLE [dbo].[KullaniciAdresMapping] DROP CONSTRAINT [FK_dbo.KullaniciAdresMapping_dbo.Adres_AdresId];


GO
PRINT N'Dropping [dbo].[FK_dbo.SaticiMekanMapping_dbo.Adres_AdresId]...';


GO
ALTER TABLE [dbo].[SaticiMekanMapping] DROP CONSTRAINT [FK_dbo.SaticiMekanMapping_dbo.Adres_AdresId];


GO
PRINT N'Dropping [dbo].[FK_dbo.Siparis_dbo.Adres_KargoAdresId]...';


GO
ALTER TABLE [dbo].[Siparis] DROP CONSTRAINT [FK_dbo.Siparis_dbo.Adres_KargoAdresId];


GO
PRINT N'Dropping [dbo].[FK_dbo.KullaniciAdresMapping_dbo.AspNetUsers_KullaniciId]...';


GO
ALTER TABLE [dbo].[KullaniciAdresMapping] DROP CONSTRAINT [FK_dbo.KullaniciAdresMapping_dbo.AspNetUsers_KullaniciId];


GO
PRINT N'Dropping [dbo].[FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId]...';


GO
ALTER TABLE [dbo].[AspNetUserClaims] DROP CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId];


GO
PRINT N'Dropping [dbo].[FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId]...';


GO
ALTER TABLE [dbo].[AspNetUserLogins] DROP CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId];


GO
PRINT N'Dropping [dbo].[FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId]...';


GO
ALTER TABLE [dbo].[AspNetUserRoles] DROP CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId];


GO
PRINT N'Dropping [dbo].[FK_dbo.SepetItem_dbo.AspNetUsers_KullaniciId]...';


GO
ALTER TABLE [dbo].[SepetItem] DROP CONSTRAINT [FK_dbo.SepetItem_dbo.AspNetUsers_KullaniciId];


GO
PRINT N'Dropping [dbo].[FK_dbo.Satici_dbo.AspNetUsers_KullaniciId]...';


GO
ALTER TABLE [dbo].[Satici] DROP CONSTRAINT [FK_dbo.Satici_dbo.AspNetUsers_KullaniciId];


GO
PRINT N'Dropping [dbo].[FK_dbo.Siparis_dbo.AspNetUsers_KullaniciId]...';


GO
ALTER TABLE [dbo].[Siparis] DROP CONSTRAINT [FK_dbo.Siparis_dbo.AspNetUsers_KullaniciId];


GO
PRINT N'Dropping [dbo].[FK_dbo.UrunResimMapping_dbo.Resim_ResimId]...';


GO
ALTER TABLE [dbo].[UrunResimMapping] DROP CONSTRAINT [FK_dbo.UrunResimMapping_dbo.Resim_ResimId];


GO
PRINT N'Dropping [dbo].[FK_dbo.SaticiMekanMapping_dbo.Satici_SaticiId]...';


GO
ALTER TABLE [dbo].[SaticiMekanMapping] DROP CONSTRAINT [FK_dbo.SaticiMekanMapping_dbo.Satici_SaticiId];


GO
PRINT N'Dropping [dbo].[FK_dbo.SepetItem_dbo.Urun_UrunId]...';


GO
ALTER TABLE [dbo].[SepetItem] DROP CONSTRAINT [FK_dbo.SepetItem_dbo.Urun_UrunId];


GO
PRINT N'Dropping [dbo].[FK_dbo.SiparisItem_dbo.Siparis_SiparisId]...';


GO
ALTER TABLE [dbo].[SiparisItem] DROP CONSTRAINT [FK_dbo.SiparisItem_dbo.Siparis_SiparisId];


GO
PRINT N'Dropping [dbo].[FK_dbo.SiparisItem_dbo.Satici_SaticiId]...';


GO
ALTER TABLE [dbo].[SiparisItem] DROP CONSTRAINT [FK_dbo.SiparisItem_dbo.Satici_SaticiId];


GO
PRINT N'Dropping [dbo].[FK_dbo.SiparisItem_dbo.Urun_UrunId]...';


GO
ALTER TABLE [dbo].[SiparisItem] DROP CONSTRAINT [FK_dbo.SiparisItem_dbo.Urun_UrunId];


GO
PRINT N'Starting rebuilding table [dbo].[Adres]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Adres] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [Baslik]      NVARCHAR (150) NOT NULL,
    [Adres]       NVARCHAR (MAX) NOT NULL,
    [IlceId]      INT            NOT NULL,
    [Telefon]     NCHAR (15)     NULL,
    [CreatedDate] DATETIME       NOT NULL,
    [Aktif]       BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_dbo.Adres1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Adres])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Adres] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Adres] ([Id], [Baslik], [Adres], [IlceId], [Telefon], [Aktif], [CreatedDate])
        SELECT   [Id],
                 [Baslik],
                 [Adres],
                 [IlceId],
                 [Telefon],
                 [Aktif],
                 [CreatedDate]
        FROM     [dbo].[Adres]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Adres] OFF;
    END

DROP TABLE [dbo].[Adres];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Adres]', N'Adres';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_dbo.Adres1]', N'PK_dbo.Adres', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[Adres].[IX_IlceId]...';


GO
CREATE NONCLUSTERED INDEX [IX_IlceId]
    ON [dbo].[Adres]([IlceId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[AspNetUsers]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_AspNetUsers] (
    [Id]                   NVARCHAR (128) NOT NULL,
    [CreatedDate]          DATETIME       NOT NULL,
    [UpdatedDate]          DATETIME       NOT NULL,
    [IsDeleted]            BIT            NOT NULL,
    [IsActive]             BIT            NOT NULL,
    [Email]                NVARCHAR (256) NULL,
    [EmailConfirmed]       BIT            NOT NULL,
    [PasswordHash]         NVARCHAR (MAX) NULL,
    [SecurityStamp]        NVARCHAR (MAX) NULL,
    [PhoneNumber]          NVARCHAR (MAX) NULL,
    [PhoneNumberConfirmed] BIT            NOT NULL,
    [TwoFactorEnabled]     BIT            NOT NULL,
    [LockoutEndDateUtc]    DATETIME       NULL,
    [LockoutEnabled]       BIT            NOT NULL,
    [AccessFailedCount]    INT            NOT NULL,
    [UserName]             NVARCHAR (256) NOT NULL,
    [Ad]                   NVARCHAR (MAX) NULL,
    [Soyad]                NVARCHAR (MAX) NULL,
    [ResimId]              INT            NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_dbo.AspNetUsers1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[AspNetUsers])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_AspNetUsers] ([Id], [Ad], [Soyad], [CreatedDate], [UpdatedDate], [IsDeleted], [IsActive], [ResimId], [Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName])
        SELECT   [Id],
                 [Ad],
                 [Soyad],
                 [CreatedDate],
                 [UpdatedDate],
                 [IsDeleted],
                 [IsActive],
                 [ResimId],
                 [Email],
                 [EmailConfirmed],
                 [PasswordHash],
                 [SecurityStamp],
                 [PhoneNumber],
                 [PhoneNumberConfirmed],
                 [TwoFactorEnabled],
                 [LockoutEndDateUtc],
                 [LockoutEnabled],
                 [AccessFailedCount],
                 [UserName]
        FROM     [dbo].[AspNetUsers]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[AspNetUsers];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_AspNetUsers]', N'AspNetUsers';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_dbo.AspNetUsers1]', N'PK_dbo.AspNetUsers', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[AspNetUsers].[UserNameIndex]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UserNameIndex]
    ON [dbo].[AspNetUsers]([UserName] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[Resim]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Resim] (
    [Id]          INT             IDENTITY (1, 1) NOT NULL,
    [ResimBinary] VARBINARY (MAX) NULL,
    [Baslik]      NVARCHAR (MAX)  NULL,
    [AltAttr]     NVARCHAR (MAX)  NULL,
    [TitleAttr]   NVARCHAR (MAX)  NULL,
    [CreatedDate] DATETIME        NOT NULL,
    [ResimPath]   NVARCHAR (MAX)  NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_dbo.Resim1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Resim])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Resim] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Resim] ([Id], [ResimBinary], [ResimPath], [Baslik], [AltAttr], [TitleAttr], [CreatedDate])
        SELECT   [Id],
                 [ResimBinary],
                 [ResimPath],
                 [Baslik],
                 [AltAttr],
                 [TitleAttr],
                 [CreatedDate]
        FROM     [dbo].[Resim]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Resim] OFF;
    END

DROP TABLE [dbo].[Resim];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Resim]', N'Resim';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_dbo.Resim1]', N'PK_dbo.Resim', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[SaticiMekanMapping]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_SaticiMekanMapping] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [SaticiId]    INT            NOT NULL,
    [AdresId]     INT            NOT NULL,
    [Aciklama]    NVARCHAR (500) NULL,
    [CreatedDate] DATETIME       NOT NULL,
    [UpdatedDate] DATETIME       NOT NULL,
    [Aktif]       BIT            DEFAULT ((0)) NOT NULL,
    [Silindi]     BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_dbo.SaticiMekanMapping1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[SaticiMekanMapping])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_SaticiMekanMapping] ON;
        INSERT INTO [dbo].[tmp_ms_xx_SaticiMekanMapping] ([Id], [SaticiId], [AdresId], [Aciklama], [Aktif], [Silindi], [CreatedDate], [UpdatedDate])
        SELECT   [Id],
                 [SaticiId],
                 [AdresId],
                 [Aciklama],
                 [Aktif],
                 [Silindi],
                 [CreatedDate],
                 [UpdatedDate]
        FROM     [dbo].[SaticiMekanMapping]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_SaticiMekanMapping] OFF;
    END

DROP TABLE [dbo].[SaticiMekanMapping];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_SaticiMekanMapping]', N'SaticiMekanMapping';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_dbo.SaticiMekanMapping1]', N'PK_dbo.SaticiMekanMapping', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[SaticiMekanMapping].[IX_AdresId]...';


GO
CREATE NONCLUSTERED INDEX [IX_AdresId]
    ON [dbo].[SaticiMekanMapping]([AdresId] ASC);


GO
PRINT N'Creating [dbo].[SaticiMekanMapping].[IX_SaticiId]...';


GO
CREATE NONCLUSTERED INDEX [IX_SaticiId]
    ON [dbo].[SaticiMekanMapping]([SaticiId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[SepetItem]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_SepetItem] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [KullaniciId] NVARCHAR (128) NOT NULL,
    [UrunId]      INT            NOT NULL,
    [Miktar]      INT            NOT NULL,
    [CreatedDate] DATETIME       NOT NULL,
    [UpdatedDate] DATETIME       NOT NULL,
    [Aktif]       BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_dbo.SepetItem1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[SepetItem])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_SepetItem] ON;
        INSERT INTO [dbo].[tmp_ms_xx_SepetItem] ([Id], [KullaniciId], [UrunId], [Miktar], [Aktif], [CreatedDate], [UpdatedDate])
        SELECT   [Id],
                 [KullaniciId],
                 [UrunId],
                 [Miktar],
                 [Aktif],
                 [CreatedDate],
                 [UpdatedDate]
        FROM     [dbo].[SepetItem]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_SepetItem] OFF;
    END

DROP TABLE [dbo].[SepetItem];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_SepetItem]', N'SepetItem';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_dbo.SepetItem1]', N'PK_dbo.SepetItem', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[SepetItem].[IX_KullaniciId]...';


GO
CREATE NONCLUSTERED INDEX [IX_KullaniciId]
    ON [dbo].[SepetItem]([KullaniciId] ASC);


GO
PRINT N'Creating [dbo].[SepetItem].[IX_UrunId]...';


GO
CREATE NONCLUSTERED INDEX [IX_UrunId]
    ON [dbo].[SepetItem]([UrunId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[Siparis]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Siparis] (
    [Id]                 INT              IDENTITY (1, 1) NOT NULL,
    [SiparisGuid]        UNIQUEIDENTIFIER NOT NULL,
    [KullaniciId]        NVARCHAR (128)   NOT NULL,
    [KargoAdresId]       INT              NOT NULL,
    [SiparisDurumId]     INT              NULL,
    [OdemeDurumId]       INT              NULL,
    [KargoDurumId]       INT              NULL,
    [SiparisToplam]      DECIMAL (18)     NOT NULL,
    [Aktif]              BIT              NOT NULL,
    [Silindi]            BIT              NOT NULL,
    [KartAdi]            NVARCHAR (MAX)   NULL,
    [KartNumarasi]       NVARCHAR (MAX)   NULL,
    [KartCvv]            NVARCHAR (MAX)   NULL,
    [KartSonKullanimAy]  NVARCHAR (MAX)   NULL,
    [KartSonKullanimYil] NVARCHAR (MAX)   NULL,
    [Tarih]              DATETIME         DEFAULT ('1900-01-01T00:00:00.000') NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_dbo.Siparis1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Siparis])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Siparis] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Siparis] ([Id], [SiparisGuid], [KullaniciId], [KargoAdresId], [SiparisDurumId], [OdemeDurumId], [KargoDurumId], [SiparisToplam], [KartAdi], [KartNumarasi], [KartCvv], [KartSonKullanimAy], [KartSonKullanimYil], [Aktif], [Silindi], [Tarih])
        SELECT   [Id],
                 [SiparisGuid],
                 [KullaniciId],
                 [KargoAdresId],
                 [SiparisDurumId],
                 [OdemeDurumId],
                 [KargoDurumId],
                 [SiparisToplam],
                 [KartAdi],
                 [KartNumarasi],
                 [KartCvv],
                 [KartSonKullanimAy],
                 [KartSonKullanimYil],
                 [Aktif],
                 [Silindi],
                 [Tarih]
        FROM     [dbo].[Siparis]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Siparis] OFF;
    END

DROP TABLE [dbo].[Siparis];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Siparis]', N'Siparis';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_dbo.Siparis1]', N'PK_dbo.Siparis', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[Siparis].[IX_KargoAdresId]...';


GO
CREATE NONCLUSTERED INDEX [IX_KargoAdresId]
    ON [dbo].[Siparis]([KargoAdresId] ASC);


GO
PRINT N'Creating [dbo].[Siparis].[IX_KullaniciId]...';


GO
CREATE NONCLUSTERED INDEX [IX_KullaniciId]
    ON [dbo].[Siparis]([KullaniciId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[SiparisItem]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_SiparisItem] (
    [Id]              INT              IDENTITY (1, 1) NOT NULL,
    [SiparisItemGuid] UNIQUEIDENTIFIER NOT NULL,
    [SiparisId]       INT              NOT NULL,
    [UrunId]          INT              NOT NULL,
    [Miktar]          INT              NOT NULL,
    [IndirimMiktari]  DECIMAL (18, 4)  NOT NULL,
    [Fiyat]           DECIMAL (18, 4)  NOT NULL,
    [SaticiId]        INT              NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_dbo.SiparisItem1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[SiparisItem])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_SiparisItem] ON;
        INSERT INTO [dbo].[tmp_ms_xx_SiparisItem] ([Id], [SiparisItemGuid], [SiparisId], [UrunId], [Miktar], [SaticiId], [IndirimMiktari], [Fiyat])
        SELECT   [Id],
                 [SiparisItemGuid],
                 [SiparisId],
                 [UrunId],
                 [Miktar],
                 [SaticiId],
                 [IndirimMiktari],
                 [Fiyat]
        FROM     [dbo].[SiparisItem]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_SiparisItem] OFF;
    END

DROP TABLE [dbo].[SiparisItem];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_SiparisItem]', N'SiparisItem';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_dbo.SiparisItem1]', N'PK_dbo.SiparisItem', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[SiparisItem].[IX_SaticiId]...';


GO
CREATE NONCLUSTERED INDEX [IX_SaticiId]
    ON [dbo].[SiparisItem]([SaticiId] ASC);


GO
PRINT N'Creating [dbo].[SiparisItem].[IX_SiparisId]...';


GO
CREATE NONCLUSTERED INDEX [IX_SiparisId]
    ON [dbo].[SiparisItem]([SiparisId] ASC);


GO
PRINT N'Creating [dbo].[SiparisItem].[IX_UrunId]...';


GO
CREATE NONCLUSTERED INDEX [IX_UrunId]
    ON [dbo].[SiparisItem]([UrunId] ASC);


GO
PRINT N'Creating [dbo].[Kargo]...';


GO
CREATE TABLE [dbo].[Kargo] (
    [Id]              INT      IDENTITY (1, 1) NOT NULL,
    [SiparisId]       INT      NOT NULL,
    [KargolamaTarihi] DATETIME NULL,
    [TeslimTarihi]    DATETIME NULL,
    [CreatedDate]     DATETIME NOT NULL,
    CONSTRAINT [PK_dbo.Kargo] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Kargo].[IX_SiparisId]...';


GO
CREATE NONCLUSTERED INDEX [IX_SiparisId]
    ON [dbo].[Kargo]([SiparisId] ASC);


GO
PRINT N'Creating [dbo].[KargoItem]...';


GO
CREATE TABLE [dbo].[KargoItem] (
    [Id]            INT IDENTITY (1, 1) NOT NULL,
    [KargoId]       INT NOT NULL,
    [SiparisItemId] INT NOT NULL,
    [Miktar]        INT NOT NULL,
    CONSTRAINT [PK_dbo.KargoItem] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[KargoItem].[IX_KargoId]...';


GO
CREATE NONCLUSTERED INDEX [IX_KargoId]
    ON [dbo].[KargoItem]([KargoId] ASC);


GO
PRINT N'Creating [dbo].[KargoItem].[IX_SiparisItemId]...';


GO
CREATE NONCLUSTERED INDEX [IX_SiparisItemId]
    ON [dbo].[KargoItem]([SiparisItemId] ASC);


GO
PRINT N'Creating [dbo].[KategoriIndirimMapping]...';


GO
CREATE TABLE [dbo].[KategoriIndirimMapping] (
    [Id]         INT IDENTITY (1, 1) NOT NULL,
    [KategoriId] INT NOT NULL,
    [IndirimId]  INT NOT NULL,
    CONSTRAINT [PK_dbo.KategoriIndirimMapping] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[KategoriIndirimMapping].[IX_IndirimId]...';


GO
CREATE NONCLUSTERED INDEX [IX_IndirimId]
    ON [dbo].[KategoriIndirimMapping]([IndirimId] ASC);


GO
PRINT N'Creating [dbo].[KategoriIndirimMapping].[IX_KategoriId]...';


GO
CREATE NONCLUSTERED INDEX [IX_KategoriId]
    ON [dbo].[KategoriIndirimMapping]([KategoriId] ASC);


GO
PRINT N'Creating [dbo].[Log]...';


GO
CREATE TABLE [dbo].[Log] (
    [Id]     INT            IDENTITY (1, 1) NOT NULL,
    [Action] NVARCHAR (250) NOT NULL,
    CONSTRAINT [PK_dbo.Log] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[UrunOzellik]...';


GO
CREATE TABLE [dbo].[UrunOzellik] (
    [Id] INT            IDENTITY (1, 1) NOT NULL,
    [Ad] NVARCHAR (250) NOT NULL,
    CONSTRAINT [PK_dbo.UrunOzellik] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[UrunOzellikDeger]...';


GO
CREATE TABLE [dbo].[UrunOzellikDeger] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [UrunOzellikMappingId] INT            NOT NULL,
    [OzellikDegerTipId]    INT            NOT NULL,
    [Ad]                   NVARCHAR (250) NOT NULL,
    CONSTRAINT [PK_dbo.UrunOzellikDeger] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[UrunOzellikDeger].[IX_UrunOzellikMappingId]...';


GO
CREATE NONCLUSTERED INDEX [IX_UrunOzellikMappingId]
    ON [dbo].[UrunOzellikDeger]([UrunOzellikMappingId] ASC);


GO
PRINT N'Creating [dbo].[UrunOzellikMapping]...';


GO
CREATE TABLE [dbo].[UrunOzellikMapping] (
    [Id]                  INT IDENTITY (1, 1) NOT NULL,
    [UrunId]              INT NOT NULL,
    [UrunOzellikId]       INT NOT NULL,
    [OzellikControlTipId] INT NOT NULL,
    CONSTRAINT [PK_dbo.UrunOzellikMapping] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[UrunOzellikMapping].[IX_UrunId]...';


GO
CREATE NONCLUSTERED INDEX [IX_UrunId]
    ON [dbo].[UrunOzellikMapping]([UrunId] ASC);


GO
PRINT N'Creating [dbo].[UrunOzellikMapping].[IX_UrunOzellikId]...';


GO
CREATE NONCLUSTERED INDEX [IX_UrunOzellikId]
    ON [dbo].[UrunOzellikMapping]([UrunOzellikId] ASC);


GO
PRINT N'Creating [dbo].[FK_dbo.Adres_dbo.Ilce_IlceId]...';


GO
ALTER TABLE [dbo].[Adres] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.Adres_dbo.Ilce_IlceId] FOREIGN KEY ([IlceId]) REFERENCES [dbo].[Ilce] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.KullaniciAdresMapping_dbo.Adres_AdresId]...';


GO
ALTER TABLE [dbo].[KullaniciAdresMapping] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.KullaniciAdresMapping_dbo.Adres_AdresId] FOREIGN KEY ([AdresId]) REFERENCES [dbo].[Adres] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.SaticiMekanMapping_dbo.Adres_AdresId]...';


GO
ALTER TABLE [dbo].[SaticiMekanMapping] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.SaticiMekanMapping_dbo.Adres_AdresId] FOREIGN KEY ([AdresId]) REFERENCES [dbo].[Adres] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.Siparis_dbo.Adres_KargoAdresId]...';


GO
ALTER TABLE [dbo].[Siparis] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.Siparis_dbo.Adres_KargoAdresId] FOREIGN KEY ([KargoAdresId]) REFERENCES [dbo].[Adres] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.KullaniciAdresMapping_dbo.AspNetUsers_KullaniciId]...';


GO
ALTER TABLE [dbo].[KullaniciAdresMapping] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.KullaniciAdresMapping_dbo.AspNetUsers_KullaniciId] FOREIGN KEY ([KullaniciId]) REFERENCES [dbo].[AspNetUsers] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId]...';


GO
ALTER TABLE [dbo].[AspNetUserClaims] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId]...';


GO
ALTER TABLE [dbo].[AspNetUserLogins] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId]...';


GO
ALTER TABLE [dbo].[AspNetUserRoles] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_dbo.SepetItem_dbo.AspNetUsers_KullaniciId]...';


GO
ALTER TABLE [dbo].[SepetItem] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.SepetItem_dbo.AspNetUsers_KullaniciId] FOREIGN KEY ([KullaniciId]) REFERENCES [dbo].[AspNetUsers] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.Satici_dbo.AspNetUsers_KullaniciId]...';


GO
ALTER TABLE [dbo].[Satici] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.Satici_dbo.AspNetUsers_KullaniciId] FOREIGN KEY ([KullaniciId]) REFERENCES [dbo].[AspNetUsers] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.Siparis_dbo.AspNetUsers_KullaniciId]...';


GO
ALTER TABLE [dbo].[Siparis] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.Siparis_dbo.AspNetUsers_KullaniciId] FOREIGN KEY ([KullaniciId]) REFERENCES [dbo].[AspNetUsers] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.UrunResimMapping_dbo.Resim_ResimId]...';


GO
ALTER TABLE [dbo].[UrunResimMapping] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.UrunResimMapping_dbo.Resim_ResimId] FOREIGN KEY ([ResimId]) REFERENCES [dbo].[Resim] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.SaticiMekanMapping_dbo.Satici_SaticiId]...';


GO
ALTER TABLE [dbo].[SaticiMekanMapping] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.SaticiMekanMapping_dbo.Satici_SaticiId] FOREIGN KEY ([SaticiId]) REFERENCES [dbo].[Satici] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.SepetItem_dbo.Urun_UrunId]...';


GO
ALTER TABLE [dbo].[SepetItem] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.SepetItem_dbo.Urun_UrunId] FOREIGN KEY ([UrunId]) REFERENCES [dbo].[Urun] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.SiparisItem_dbo.Siparis_SiparisId]...';


GO
ALTER TABLE [dbo].[SiparisItem] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.SiparisItem_dbo.Siparis_SiparisId] FOREIGN KEY ([SiparisId]) REFERENCES [dbo].[Siparis] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.SiparisItem_dbo.Satici_SaticiId]...';


GO
ALTER TABLE [dbo].[SiparisItem] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.SiparisItem_dbo.Satici_SaticiId] FOREIGN KEY ([SaticiId]) REFERENCES [dbo].[Satici] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_dbo.SiparisItem_dbo.Urun_UrunId]...';


GO
ALTER TABLE [dbo].[SiparisItem] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.SiparisItem_dbo.Urun_UrunId] FOREIGN KEY ([UrunId]) REFERENCES [dbo].[Urun] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.Kargo_dbo.Siparis_SiparisId]...';


GO
ALTER TABLE [dbo].[Kargo] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.Kargo_dbo.Siparis_SiparisId] FOREIGN KEY ([SiparisId]) REFERENCES [dbo].[Siparis] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.KargoItem_dbo.Kargo_KargoId]...';


GO
ALTER TABLE [dbo].[KargoItem] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.KargoItem_dbo.Kargo_KargoId] FOREIGN KEY ([KargoId]) REFERENCES [dbo].[Kargo] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.KargoItem_dbo.SiparisItem_SiparisItemId]...';


GO
ALTER TABLE [dbo].[KargoItem] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.KargoItem_dbo.SiparisItem_SiparisItemId] FOREIGN KEY ([SiparisItemId]) REFERENCES [dbo].[SiparisItem] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.KategoriIndirimMapping_dbo.Indirim_IndirimId]...';


GO
ALTER TABLE [dbo].[KategoriIndirimMapping] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.KategoriIndirimMapping_dbo.Indirim_IndirimId] FOREIGN KEY ([IndirimId]) REFERENCES [dbo].[Indirim] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.KategoriIndirimMapping_dbo.Kategori_KategoriId]...';


GO
ALTER TABLE [dbo].[KategoriIndirimMapping] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.KategoriIndirimMapping_dbo.Kategori_KategoriId] FOREIGN KEY ([KategoriId]) REFERENCES [dbo].[Kategori] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.UrunOzellikDeger_dbo.UrunOzellikMapping_UrunOzellikMappingId]...';


GO
ALTER TABLE [dbo].[UrunOzellikDeger] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.UrunOzellikDeger_dbo.UrunOzellikMapping_UrunOzellikMappingId] FOREIGN KEY ([UrunOzellikMappingId]) REFERENCES [dbo].[UrunOzellikMapping] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.UrunOzellikMapping_dbo.Urun_UrunId]...';


GO
ALTER TABLE [dbo].[UrunOzellikMapping] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.UrunOzellikMapping_dbo.Urun_UrunId] FOREIGN KEY ([UrunId]) REFERENCES [dbo].[Urun] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.UrunOzellikMapping_dbo.UrunOzellik_UrunOzellikId]...';


GO
ALTER TABLE [dbo].[UrunOzellikMapping] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.UrunOzellikMapping_dbo.UrunOzellik_UrunOzellikId] FOREIGN KEY ([UrunOzellikId]) REFERENCES [dbo].[UrunOzellik] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Adres] WITH CHECK CHECK CONSTRAINT [FK_dbo.Adres_dbo.Ilce_IlceId];

ALTER TABLE [dbo].[KullaniciAdresMapping] WITH CHECK CHECK CONSTRAINT [FK_dbo.KullaniciAdresMapping_dbo.Adres_AdresId];

ALTER TABLE [dbo].[SaticiMekanMapping] WITH CHECK CHECK CONSTRAINT [FK_dbo.SaticiMekanMapping_dbo.Adres_AdresId];

ALTER TABLE [dbo].[Siparis] WITH CHECK CHECK CONSTRAINT [FK_dbo.Siparis_dbo.Adres_KargoAdresId];

ALTER TABLE [dbo].[KullaniciAdresMapping] WITH CHECK CHECK CONSTRAINT [FK_dbo.KullaniciAdresMapping_dbo.AspNetUsers_KullaniciId];

ALTER TABLE [dbo].[AspNetUserClaims] WITH CHECK CHECK CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId];

ALTER TABLE [dbo].[AspNetUserLogins] WITH CHECK CHECK CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId];

ALTER TABLE [dbo].[AspNetUserRoles] WITH CHECK CHECK CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId];

ALTER TABLE [dbo].[SepetItem] WITH CHECK CHECK CONSTRAINT [FK_dbo.SepetItem_dbo.AspNetUsers_KullaniciId];

ALTER TABLE [dbo].[Satici] WITH CHECK CHECK CONSTRAINT [FK_dbo.Satici_dbo.AspNetUsers_KullaniciId];

ALTER TABLE [dbo].[Siparis] WITH CHECK CHECK CONSTRAINT [FK_dbo.Siparis_dbo.AspNetUsers_KullaniciId];

ALTER TABLE [dbo].[UrunResimMapping] WITH CHECK CHECK CONSTRAINT [FK_dbo.UrunResimMapping_dbo.Resim_ResimId];

ALTER TABLE [dbo].[SaticiMekanMapping] WITH CHECK CHECK CONSTRAINT [FK_dbo.SaticiMekanMapping_dbo.Satici_SaticiId];

ALTER TABLE [dbo].[SepetItem] WITH CHECK CHECK CONSTRAINT [FK_dbo.SepetItem_dbo.Urun_UrunId];

ALTER TABLE [dbo].[SiparisItem] WITH CHECK CHECK CONSTRAINT [FK_dbo.SiparisItem_dbo.Siparis_SiparisId];

ALTER TABLE [dbo].[SiparisItem] WITH CHECK CHECK CONSTRAINT [FK_dbo.SiparisItem_dbo.Satici_SaticiId];

ALTER TABLE [dbo].[SiparisItem] WITH CHECK CHECK CONSTRAINT [FK_dbo.SiparisItem_dbo.Urun_UrunId];

ALTER TABLE [dbo].[Kargo] WITH CHECK CHECK CONSTRAINT [FK_dbo.Kargo_dbo.Siparis_SiparisId];

ALTER TABLE [dbo].[KargoItem] WITH CHECK CHECK CONSTRAINT [FK_dbo.KargoItem_dbo.Kargo_KargoId];

ALTER TABLE [dbo].[KargoItem] WITH CHECK CHECK CONSTRAINT [FK_dbo.KargoItem_dbo.SiparisItem_SiparisItemId];

ALTER TABLE [dbo].[KategoriIndirimMapping] WITH CHECK CHECK CONSTRAINT [FK_dbo.KategoriIndirimMapping_dbo.Indirim_IndirimId];

ALTER TABLE [dbo].[KategoriIndirimMapping] WITH CHECK CHECK CONSTRAINT [FK_dbo.KategoriIndirimMapping_dbo.Kategori_KategoriId];

ALTER TABLE [dbo].[UrunOzellikDeger] WITH CHECK CHECK CONSTRAINT [FK_dbo.UrunOzellikDeger_dbo.UrunOzellikMapping_UrunOzellikMappingId];

ALTER TABLE [dbo].[UrunOzellikMapping] WITH CHECK CHECK CONSTRAINT [FK_dbo.UrunOzellikMapping_dbo.Urun_UrunId];

ALTER TABLE [dbo].[UrunOzellikMapping] WITH CHECK CHECK CONSTRAINT [FK_dbo.UrunOzellikMapping_dbo.UrunOzellik_UrunOzellikId];


GO
PRINT N'Update complete.';


GO
